import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const [,, scheme='dark', W='390', H='844', tag='m'] = process.argv;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:+W,height:+H}, deviceScaleFactor: +W>800?2:3, colorScheme:scheme, locale:'es-MX', timezoneId:'America/Tijuana', serviceWorkers:'block', reducedMotion:'reduce' });
const p = await ctx.newPage();
const u='http://localhost:4173';
const snap = async (n)=>{ await p.waitForTimeout(900); await p.screenshot({path:`${tag}-${scheme}-${n}.png`}); };
await p.goto(u+'/bienvenida'); await snap('01-bienvenida');
await p.getByText('Cargar datos de ejemplo').click(); await p.waitForTimeout(2500);
await p.goto(u+'/'); await snap('02-hoy');
await p.goto(u+'/progreso'); await snap('05-progreso');
await p.goto(u+'/progreso/sentadilla'); await snap('06-ejercicio');
await p.goto(u+'/historial'); await snap('07-historial');
await p.goto(u+'/biblioteca'); await snap('08-biblioteca');
await p.goto(u+'/programas'); await p.getByText('Torso / Pierna (ejemplo)').first().click(); await snap('09-programa');
await p.goto(u+'/'); await p.getByText(/^Empezar/).first().click(); await p.waitForTimeout(1200);
await snap('03a-sesion');
const regs = p.locator('[aria-label^="Registrar serie"]');
await regs.nth(0).click(); await p.waitForTimeout(600);
await regs.nth(0).click(); await p.waitForTimeout(3000);
await snap('03-sesion');
await b.close();
